// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filter/filter.proto

package querySuggestion

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilterType int32

const (
	FilterType_SINGLE FilterType = 0
	FilterType_RANGE  FilterType = 1
)

var FilterType_name = map[int32]string{
	0: "SINGLE",
	1: "RANGE",
}

var FilterType_value = map[string]int32{
	"SINGLE": 0,
	"RANGE":  1,
}

func (x FilterType) String() string {
	return proto.EnumName(FilterType_name, int32(x))
}

func (FilterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f45b4a1fb0c46f6e, []int{0}
}

type RangeValue struct {
	Start                float32  `protobuf:"fixed32,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  float32  `protobuf:"fixed32,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeValue) Reset()         { *m = RangeValue{} }
func (m *RangeValue) String() string { return proto.CompactTextString(m) }
func (*RangeValue) ProtoMessage()    {}
func (*RangeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f45b4a1fb0c46f6e, []int{0}
}

func (m *RangeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeValue.Unmarshal(m, b)
}
func (m *RangeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeValue.Marshal(b, m, deterministic)
}
func (m *RangeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeValue.Merge(m, src)
}
func (m *RangeValue) XXX_Size() int {
	return xxx_messageInfo_RangeValue.Size(m)
}
func (m *RangeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeValue.DiscardUnknown(m)
}

var xxx_messageInfo_RangeValue proto.InternalMessageInfo

func (m *RangeValue) GetStart() float32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *RangeValue) GetEnd() float32 {
	if m != nil {
		return m.End
	}
	return 0
}

type FilterItem struct {
	// Types that are valid to be assigned to Value:
	//	*FilterItem_Label
	//	*FilterItem_Range
	Value                isFilterItem_Value     `protobuf_oneof:"value"`
	Items                map[string]*FilterItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FilterItem) Reset()         { *m = FilterItem{} }
func (m *FilterItem) String() string { return proto.CompactTextString(m) }
func (*FilterItem) ProtoMessage()    {}
func (*FilterItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f45b4a1fb0c46f6e, []int{1}
}

func (m *FilterItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterItem.Unmarshal(m, b)
}
func (m *FilterItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterItem.Marshal(b, m, deterministic)
}
func (m *FilterItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterItem.Merge(m, src)
}
func (m *FilterItem) XXX_Size() int {
	return xxx_messageInfo_FilterItem.Size(m)
}
func (m *FilterItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterItem.DiscardUnknown(m)
}

var xxx_messageInfo_FilterItem proto.InternalMessageInfo

type isFilterItem_Value interface {
	isFilterItem_Value()
}

type FilterItem_Label struct {
	Label string `protobuf:"bytes,1,opt,name=label,proto3,oneof"`
}

type FilterItem_Range struct {
	Range *RangeValue `protobuf:"bytes,2,opt,name=range,proto3,oneof"`
}

func (*FilterItem_Label) isFilterItem_Value() {}

func (*FilterItem_Range) isFilterItem_Value() {}

func (m *FilterItem) GetValue() isFilterItem_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *FilterItem) GetLabel() string {
	if x, ok := m.GetValue().(*FilterItem_Label); ok {
		return x.Label
	}
	return ""
}

func (m *FilterItem) GetRange() *RangeValue {
	if x, ok := m.GetValue().(*FilterItem_Range); ok {
		return x.Range
	}
	return nil
}

func (m *FilterItem) GetItems() map[string]*FilterItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FilterItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FilterItem_Label)(nil),
		(*FilterItem_Range)(nil),
	}
}

type Filter struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attribute            string                 `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Label                string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Type                 FilterType             `protobuf:"varint,4,opt,name=type,proto3,enum=querySuggestion.FilterType" json:"type,omitempty"`
	Items                map[string]*FilterItem `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f45b4a1fb0c46f6e, []int{2}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Filter) GetAttribute() string {
	if m != nil {
		return m.Attribute
	}
	return ""
}

func (m *Filter) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Filter) GetType() FilterType {
	if m != nil {
		return m.Type
	}
	return FilterType_SINGLE
}

func (m *Filter) GetItems() map[string]*FilterItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("querySuggestion.FilterType", FilterType_name, FilterType_value)
	proto.RegisterType((*RangeValue)(nil), "querySuggestion.RangeValue")
	proto.RegisterType((*FilterItem)(nil), "querySuggestion.FilterItem")
	proto.RegisterMapType((map[string]*FilterItem)(nil), "querySuggestion.FilterItem.ItemsEntry")
	proto.RegisterType((*Filter)(nil), "querySuggestion.Filter")
	proto.RegisterMapType((map[string]*FilterItem)(nil), "querySuggestion.Filter.ItemsEntry")
}

func init() { proto.RegisterFile("filter/filter.proto", fileDescriptor_f45b4a1fb0c46f6e) }

var fileDescriptor_f45b4a1fb0c46f6e = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0x6e, 0x92, 0x6e, 0x5f, 0x32, 0x85, 0xbe, 0x65, 0x14, 0x09, 0xea, 0xa1, 0x44, 0x90, 0xe2,
	0x21, 0xc5, 0xd6, 0x43, 0x11, 0x2f, 0x0a, 0xb5, 0x16, 0xa4, 0x87, 0xad, 0x7a, 0x4f, 0xe9, 0x58,
	0x82, 0x69, 0x5a, 0x37, 0x13, 0x21, 0x7f, 0xc2, 0xbf, 0xeb, 0x55, 0x76, 0xb7, 0x25, 0xa0, 0xf4,
	0xea, 0x25, 0xd9, 0x9d, 0x7d, 0xbe, 0x78, 0x18, 0x38, 0x78, 0x4d, 0x52, 0x26, 0xd5, 0xb3, 0xbf,
	0x68, 0xa3, 0xd6, 0xbc, 0xc6, 0xff, 0xef, 0x05, 0xa9, 0x72, 0x56, 0x2c, 0x97, 0x94, 0x73, 0xb2,
	0xce, 0xc2, 0x2b, 0x00, 0x19, 0x67, 0x4b, 0x7a, 0x89, 0xd3, 0x82, 0xf0, 0x10, 0x44, 0xce, 0xb1,
	0xe2, 0xc0, 0xe9, 0x38, 0x5d, 0x57, 0xda, 0x0b, 0xb6, 0xc1, 0xa3, 0x6c, 0x11, 0xb8, 0x66, 0xa6,
	0x8f, 0xe1, 0x97, 0x03, 0x70, 0x6f, 0x74, 0x27, 0x4c, 0x2b, 0x3c, 0x02, 0x91, 0xc6, 0x73, 0x4a,
	0x0d, 0xcd, 0x7f, 0xa8, 0x49, 0x7b, 0xc5, 0x01, 0x08, 0xa5, 0xc5, 0x0d, 0xb5, 0xd9, 0x3f, 0x89,
	0x7e, 0xb8, 0x47, 0x95, 0xb5, 0x26, 0x19, 0x2c, 0xde, 0x80, 0x48, 0x98, 0x56, 0x79, 0xe0, 0x75,
	0xbc, 0x6e, 0xb3, 0x7f, 0xfe, 0x8b, 0x54, 0x19, 0x47, 0xfa, 0x93, 0x8f, 0x32, 0x56, 0xa5, 0xb4,
	0xa4, 0xe3, 0x67, 0x80, 0x6a, 0xa8, 0x93, 0xbf, 0x51, 0x69, 0x63, 0x49, 0x7d, 0xc4, 0x4b, 0x10,
	0x1f, 0xda, 0x6f, 0x6f, 0xa4, 0x4a, 0x5d, 0x5a, 0xe4, 0xb5, 0x3b, 0x74, 0xee, 0xfe, 0x6d, 0x69,
	0xe1, 0xa7, 0x0b, 0x0d, 0x0b, 0xc1, 0x16, 0xb8, 0xc9, 0x62, 0xab, 0xed, 0x26, 0x0b, 0x3c, 0x05,
	0x3f, 0x66, 0x56, 0xc9, 0xbc, 0x60, 0x2b, 0xef, 0xcb, 0x6a, 0xa0, 0xab, 0xb5, 0x1d, 0x79, 0xe6,
	0x65, 0xdb, 0x50, 0x0f, 0xea, 0x5c, 0x6e, 0x28, 0xa8, 0x77, 0x9c, 0x6e, 0x6b, 0x6f, 0x9a, 0xa7,
	0x72, 0x43, 0xd2, 0x00, 0x71, 0xb8, 0x6b, 0x47, 0x98, 0x76, 0xc2, 0x3d, 0x8c, 0x3f, 0x6b, 0xe6,
	0xe2, 0x6c, 0xb7, 0x09, 0x3a, 0x24, 0x02, 0x34, 0x66, 0x93, 0xe9, 0xf8, 0x71, 0xd4, 0xae, 0xa1,
	0x0f, 0x42, 0xde, 0x4e, 0xc7, 0xa3, 0xb6, 0x33, 0x6f, 0x98, 0xed, 0x1b, 0x7c, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x06, 0x1b, 0x33, 0x0b, 0x94, 0x02, 0x00, 0x00,
}
