// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: protos/sortType.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Type int32

const (
	Type_CORE   Type = 0
	Type_CUSTOM Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "CORE",
		1: "CUSTOM",
	}
	Type_value = map[string]int32{
		"CORE":   0,
		"CUSTOM": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_sortType_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_protos_sortType_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_protos_sortType_proto_rawDescGZIP(), []int{0}
}

type Order int32

const (
	Order_ASC  Order = 0
	Order_DESC Order = 1
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	Order_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_sortType_proto_enumTypes[1].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_protos_sortType_proto_enumTypes[1]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_protos_sortType_proto_rawDescGZIP(), []int{1}
}

type Sort int32

const (
	Sort_RELEVANCE Sort = 0
	Sort_DISCOUNT  Sort = 1
	Sort_PRICE     Sort = 2
	Sort_REVIEW    Sort = 3
	Sort_SALE      Sort = 4
	Sort_DISTANCE  Sort = 5
)

// Enum value maps for Sort.
var (
	Sort_name = map[int32]string{
		0: "RELEVANCE",
		1: "DISCOUNT",
		2: "PRICE",
		3: "REVIEW",
		4: "SALE",
		5: "DISTANCE",
	}
	Sort_value = map[string]int32{
		"RELEVANCE": 0,
		"DISCOUNT":  1,
		"PRICE":     2,
		"REVIEW":    3,
		"SALE":      4,
		"DISTANCE":  5,
	}
)

func (x Sort) Enum() *Sort {
	p := new(Sort)
	*p = x
	return p
}

func (x Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_sortType_proto_enumTypes[2].Descriptor()
}

func (Sort) Type() protoreflect.EnumType {
	return &file_protos_sortType_proto_enumTypes[2]
}

func (x Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sort.Descriptor instead.
func (Sort) EnumDescriptor() ([]byte, []int) {
	return file_protos_sortType_proto_rawDescGZIP(), []int{2}
}

type SortType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  Type  `protobuf:"varint,1,opt,name=type,proto3,enum=protos.Type" json:"type,omitempty"`
	Order Order `protobuf:"varint,2,opt,name=order,proto3,enum=protos.Order" json:"order,omitempty"`
	Sort  Sort  `protobuf:"varint,3,opt,name=sort,proto3,enum=protos.Sort" json:"sort,omitempty"`
}

func (x *SortType) Reset() {
	*x = SortType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_sortType_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortType) ProtoMessage() {}

func (x *SortType) ProtoReflect() protoreflect.Message {
	mi := &file_protos_sortType_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortType.ProtoReflect.Descriptor instead.
func (*SortType) Descriptor() ([]byte, []int) {
	return file_protos_sortType_proto_rawDescGZIP(), []int{0}
}

func (x *SortType) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_CORE
}

func (x *SortType) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ASC
}

func (x *SortType) GetSort() Sort {
	if x != nil {
		return x.Sort
	}
	return Sort_RELEVANCE
}

var File_protos_sortType_proto protoreflect.FileDescriptor

var file_protos_sortType_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22,
	0x73, 0x0a, 0x08, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a,
	0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x2a, 0x1c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x43, 0x4f, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d,
	0x10, 0x01, 0x2a, 0x1a, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x53, 0x43, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x53, 0x43, 0x10, 0x01, 0x2a, 0x52,
	0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x4c, 0x45, 0x56, 0x41,
	0x4e, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x55, 0x4e,
	0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x49, 0x43, 0x45, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x41,
	0x4c, 0x45, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45,
	0x10, 0x05, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x69, 0x75, 0x72, 0x79, 0x6b, 0x72, 0x69, 0x65, 0x67, 0x65, 0x72, 0x2f, 0x6e, 0x65, 0x73,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_sortType_proto_rawDescOnce sync.Once
	file_protos_sortType_proto_rawDescData = file_protos_sortType_proto_rawDesc
)

func file_protos_sortType_proto_rawDescGZIP() []byte {
	file_protos_sortType_proto_rawDescOnce.Do(func() {
		file_protos_sortType_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_sortType_proto_rawDescData)
	})
	return file_protos_sortType_proto_rawDescData
}

var file_protos_sortType_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protos_sortType_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_sortType_proto_goTypes = []interface{}{
	(Type)(0),        // 0: protos.Type
	(Order)(0),       // 1: protos.Order
	(Sort)(0),        // 2: protos.Sort
	(*SortType)(nil), // 3: protos.SortType
}
var file_protos_sortType_proto_depIdxs = []int32{
	0, // 0: protos.SortType.type:type_name -> protos.Type
	1, // 1: protos.SortType.order:type_name -> protos.Order
	2, // 2: protos.SortType.sort:type_name -> protos.Sort
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_sortType_proto_init() }
func file_protos_sortType_proto_init() {
	if File_protos_sortType_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_sortType_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_sortType_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_sortType_proto_goTypes,
		DependencyIndexes: file_protos_sortType_proto_depIdxs,
		EnumInfos:         file_protos_sortType_proto_enumTypes,
		MessageInfos:      file_protos_sortType_proto_msgTypes,
	}.Build()
	File_protos_sortType_proto = out.File
	file_protos_sortType_proto_rawDesc = nil
	file_protos_sortType_proto_goTypes = nil
	file_protos_sortType_proto_depIdxs = nil
}
