// Code generated by protoc-gen-go. DO NOT EDIT.
// source: querySuggestion/querySuggestion.proto

package querySuggestion

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QuerySuggestion struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySuggestion) Reset()         { *m = QuerySuggestion{} }
func (m *QuerySuggestion) String() string { return proto.CompactTextString(m) }
func (*QuerySuggestion) ProtoMessage()    {}
func (*QuerySuggestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_69ef812ed7dd556d, []int{0}
}

func (m *QuerySuggestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySuggestion.Unmarshal(m, b)
}
func (m *QuerySuggestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySuggestion.Marshal(b, m, deterministic)
}
func (m *QuerySuggestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySuggestion.Merge(m, src)
}
func (m *QuerySuggestion) XXX_Size() int {
	return xxx_messageInfo_QuerySuggestion.Size(m)
}
func (m *QuerySuggestion) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySuggestion.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySuggestion proto.InternalMessageInfo

func (m *QuerySuggestion) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*QuerySuggestion)(nil), "querySuggestion.QuerySuggestion")
}

func init() {
	proto.RegisterFile("querySuggestion/querySuggestion.proto", fileDescriptor_69ef812ed7dd556d)
}

var fileDescriptor_69ef812ed7dd556d = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x2c, 0x4d, 0x2d,
	0xaa, 0x0c, 0x2e, 0x4d, 0x4f, 0x4f, 0x2d, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x47, 0xe3, 0xeb, 0x15,
	0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xf1, 0xa3, 0x09, 0x2b, 0xa9, 0x73, 0xf1, 0x07, 0xa2, 0x0a, 0x09,
	0x89, 0x70, 0xb1, 0x82, 0x55, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x49, 0x6c,
	0x60, 0x03, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xb4, 0x63, 0x6e, 0x69, 0x00, 0x00,
	0x00,
}
